# Generated by Django 2.1.4 on 2018-12-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_data',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
